uploads = []

[[generated]]
id = "WcLWpRlupvN5kolqqp70H"
uri = "file://artifacts/structural-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "4HJu-WSjghK7j8VZEqIdS"
uri = "file://structural-master-apk.zip"
type = "unspecified"
title = "Structural Master APK - تطبيق Android"

[[outputs]]
id = "c_UUC-T7f0KK2zvKgzlDX"
uri = "file://StructuralMaster_v2.zip"
type = "unspecified"
title = "StructuralMaster v2 APK (مُحدَّث)"
